name: send image to docker hub
on:
  push:
    branches: [main]
    tags:
      - v0.* # to allow all tags use v*
      - v1.*
      - v2.*
# creating env instead of hard coding
env:
  DOCKER_HUB_REPO: asotirelis/3120-cicd
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: docker metadata tagging
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: asotirelis/3120-cicd
          tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          repository: ${{ env.DOCKER_HUB_REPO }}