# This workflow is adapted from pattonsgirl docker-workflow.yml 
# https://github.com/pattonsgirl/CEG3120/blob/main/Projects/Project4/sample-workflows/docker-workflow.yml
name: send image to docker hub
on:
  push:
    branches: [main]
    tags:
      - v0.* # to allow all tags use v*
      - v1.*
      - v2.*
# creating env instead of hard coding
env:
  DOCKER_HUB_REPO: asotirelis/3120-cicd
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: docker metadata taging
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 